language: java
after_script: mvn deploy -s .m2/settings.xml
env:
  global:
  - secure: ahWZBhwOoQb32L0TFPpaWSZynYlRiEMf6gVON7cQL9oSOFbKE2sirfc3LTxxZqsrEqPxYlaR7qdX2DyWSfXwmrk9SPTfuQmH1bkA94C++kSbLd8SlooxlP3hME/AzkbFQqA1iLJVVelRsRBJgu9Ib625xZDwYJTVs6AFuQNmKxI=
  - secure: N+VJm7y5ut5fi4bsxEVQsIfMtVlm8i8J9LRuBX2mUOqHq7NYBy7iXVdGCWz1Wwc0ApNJIN0eEnf7UKhgY4Asy3x4Qw0huDNbF0bH4spa/Wc3+JVrp6hDHvnEeSBNb1RFHGXgJG+QGR1/RA6WhrLTWqCj3kq61bE7T6gGIEHY1QQ=
